# Generated by Django 5.1.1 on 2024-09-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_catagory",
            field=models.CharField(default="Normal user", max_length=25),
            preserve_default=False,
        ),
    ]
