# Generated by Django 5.1.1 on 2024-09-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_account", "0002_userprofile_user_catagory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
