# Generated by Django 5.1.1 on 2024-10-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_account", "0003_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="admin_approved",
            field=models.BooleanField(default=True),
        ),
    ]
