# Generated by Django 5.1.1 on 2024-12-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_account', '0005_address'),
        ('cart', '0003_ordersummary_ordersummaryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User_account.address'),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
