# Generated by Django 5.1.1 on 2024-09-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255)),
                ("product_brand_name", models.CharField(max_length=255)),
                ("short_description", models.TextField()),
                ("mrp", models.DecimalField(decimal_places=2, max_digits=10)),
                ("in_stock", models.BooleanField(default=True)),
                (
                    "discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "product_image_main",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/"
                    ),
                ),
                ("unit_of_measurement", models.CharField(max_length=100)),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
            ],
        ),
    ]
