# Generated by Django 5.1.1 on 2024-10-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_brand_name",
            new_name="brand_name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_name",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="short_description",
            new_name="specification",
        ),
        migrations.AddField(
            model_name="product",
            name="minimum_order_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
