# Generated by Django 5.1.1 on 2024-11-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_category_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracharge",
            name="amount_known",
            field=models.BooleanField(default=False),
        ),
    ]
