# Generated by Django 5.1.1 on 2024-11-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_extracharge_amount_known"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extracharge",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
